version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
   

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

